blueprint:
  name: Universal Battery Warning
  description: >
    Checks selected battery devices and sends warnings to a mobile device and/or SMTP email
    based on user configuration.
  domain: automation
  input:
    battery_entities:
      name: Battery devices/entities to monitor
      description: Select battery sensors or devices with battery status.
      selector:
        target:
          entity:
            domain: sensor
            device_class: battery
    check_frequency:
      name: Check frequency (minutes)
      description: How often to check battery levels.
      default: 60
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: min
          mode: box
    battery_threshold:
      name: Battery level threshold (%)
      description: Notify if battery level is below this percentage.
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
          mode: box
    notify_device:
      name: Notify mobile app device (optional)
      description: Select mobile app device for notification.
      selector:
        device:
          integration: mobile_app
          multiple: false
    smtp_recipient:
      name: SMTP email recipient (optional)
      description: Enter an email address for SMTP notifications.
      default: ""
      selector:
        text:
    smtp_service:
      name: SMTP notify service
      description: Home Assistant notify service for SMTP.
      default: "notify.smtp_notify"
      selector:
        text:

trigger:
  - platform: time_pattern
    minutes: "/{{ check_frequency }}"

action:
  - variables:
      low_battery_entities: >
        {{ expand(battery_entities) | selectattr('state', 'defined') | selectattr('state', 'lt', battery_threshold | string) | map(attribute='name') | list }}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ low_battery_entities | length > 0 }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify_device is not none }}"
                sequence:
                  - service: "notify.mobile_app_{{ notify_device.id }}"
                    data:
                      message: "Low battery warning for devices: {{ low_battery_entities | join(', ') }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ smtp_recipient != '' }}"
                sequence:
                  - service: !input smtp_service
                    data:
                      title: "Home Assistant Battery Warning"
                      message: "Low battery on devices: {{ low_battery_entities | join(', ') }}"
                      target:
                        - !input smtp_recipient
