blueprint:
  name: E-Bike Ladegerät – Leistungsbasierte Steuerung
  description: >
    Schaltet ein E-Bike-Ladegerät über einen Smart-Plug (z.B. IKEA INSPELNING)
    zeitweise ein, prüft anhand der Leistungsaufnahme, ob ein Akku angeschlossen
    und/oder fast voll ist und schaltet den Strom wieder ab, inkl. optionaler Benachrichtigung.
  domain: automation
  input:
    plug_switch:
      name: Steckdose (Ladegerät)
      description: Smart-Plug, an dem das Ladegerät hängt (z.B. IKEA INSPELNING).
      selector:
        entity:
          domain: switch

    plug_power:
      name: Leistungssensor
      description: Entität, die die aktuelle Leistung in Watt liefert.
      selector:
        entity:
          domain: sensor

    check_interval_minutes:
      name: Prüfintervall (Minuten)
      description: Wie oft pro Stunde geprüft wird (z.B. 5 = alle 5 Minuten).
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
          mode: slider
          step: 1

    warmup_seconds:
      name: Einschalt-Wartezeit (Sekunden)
      description: Zeit zwischen Einschalten des Steckers und Leistungsprüfung.
      default: 30
      selector:
        number:
          min: 5
          max: 120
          unit_of_measurement: s
          mode: slider
          step: 5

    idle_power_watt:
      name: Leerlauf-Leistung (Watt)
      description: Leistungsschwelle, unterhalb derer kein Akku angenommen wird.
      default: 2
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: W
          mode: box
          step: 0.1

    charging_power_watt:
      name: Lade-Start-Schwelle (Watt)
      description: Leistungsschwelle, ab der ein „leer/ladender“ Akku erkannt wird.
      default: 100
      selector:
        number:
          min: 5
          max: 1000
          unit_of_measurement: W
          mode: box
          step: 1

    charged_power_watt:
      name: Fast voll / Abschalt-Schwelle (Watt)
      description: Fällt die Leistung darunter, wird Laden als beendet angesehen.
      default: 40
      selector:
        number:
          min: 1
          max: 500
          unit_of_measurement: W
          mode: box
          step: 1

    notify_entity:
      name: Notify-Entität (optional)
      description: z.B. notify.mobile_app_dein_handy oder notify.persistent_notification.
      default: ""
      selector:
        entity:
          domain: notify
          multiple: false

mode: single
max_exceeded: silent

trigger:
  - platform: time_pattern
    # alle X Minuten prüfen
    minutes: "/{{ iif(blueprint.inputs.check_interval_minutes | int > 0,
                      blueprint.inputs.check_interval_minutes | int,
                      5) }}"

condition: []

action:
  - variables:
      plug_switch: !input plug_switch
      plug_power: !input plug_power
      warmup_seconds: !input warmup_seconds
      idle_power_watt: !input idle_power_watt
      charging_power_watt: !input charging_power_watt
      charged_power_watt: !input charged_power_watt
      notify_entity: !input notify_entity

  # Steckdose einschalten, wenn sie aus ist
  - if:
      - condition: state
        entity_id: !input plug_switch
        state: "off"
    then:
      - service: switch.turn_on
        target:
          entity_id: !input plug_switch

  # Aufwärmzeit, bis das Ladegerät „richtig“ Strom zieht
  - delay:
      seconds: "{{ warmup_seconds | int }}"

  # Aktuellen Leistungswert lesen
  - variables:
      current_power: "{{ states(plug_power) | float(0) }}"

  # Fall 1: Unter Leerlauf-Schwelle → kein Akku, abschalten
  - if:
      - condition: template
        value_template: "{{ current_power < idle_power_watt | float(0) }}"
    then:
      - service: switch.turn_off
        target:
          entity_id: !input plug_switch
      - stop: "Kein Akku erkannt (unter Idle-Schwelle)."

  # Fall 2: Über Lade-Start-Schwelle → Akku lädt, an lassen
  - if:
      - condition: template
        value_template: "{{ current_power >= charging_power_watt | float(0) }}"
    then:
      - stop: "Akku lädt stark, Steckdose bleibt an."

  # Fall 3: Zwischen Idle und Lade-Start → Akku lädt/ist weit fortgeschritten.
  # Jetzt in einer Schleife warten, bis die Leistung unter charged_power_watt fällt.
  - repeat:
      sequence:
        - delay:
            seconds: 30
        - variables:
            current_power: "{{ states(plug_power) | float(0) }}"
        - if:
            - condition: template
              value_template: "{{ current_power <= charged_power_watt | float(0) }}"
          then:
            - service: switch.turn_off
              target:
                entity_id: !input plug_switch
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ notify_entity is not none and notify_entity != '' }}"
                  sequence:
                    - service: notify.send_message
                      data:
                        entity_id: "{{ notify_entity }}"
                        title: "E-Bike Akku geladen"
                        message: "Die Leistung ist unter {{ charged_power_watt }} W gefallen. Steckdose wurde ausgeschaltet."
            - stop: "Akku gilt als voll (unter Abschalt-Schwelle)."
      until:
        - condition: template
          value_template: "{{ current_power <= charged_power_watt | float(0) }}"