blueprint:
  name: IKEA Rodret - Tradfri RGB Lamp Control
  description: Control IKEA Tradfri RGB lamp with Rodret remote - On/Off and color cycling
  domain: automation
  input:
    remote:
      name: IKEA Rodret Remote
      description: Select the Rodret remote control
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: RODRET wireless dimmer/power switch
    target_light:
      name: Tradfri RGB Lamp
      description: Select the Tradfri RGB lamp to control
      selector:
        entity:
          domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      light: !input target_light
      colors:
        - [255, 0, 0]      # Red
        - [255, 127, 0]    # Orange
        - [255, 255, 0]    # Yellow
        - [0, 255, 0]      # Green
        - [0, 255, 255]    # Cyan
        - [0, 0, 255]      # Blue
        - [255, 0, 255]    # Magenta
        - [255, 255, 255]  # White
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ command == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
      
      - conditions:
          - condition: template
            value_template: "{{ command == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light }}"
      
      - conditions:
          - condition: template
            value_template: "{{ command == 'press' and trigger.event.data.args.press_type == 'short' and trigger.event.data.args.step_mode == 1 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              rgb_color: >
                {% set current = state_attr(light, 'rgb_color') %}
                {% if current %}
                  {% set idx = 0 %}
                  {% for color in colors %}
                    {% if color == current %}
                      {% set idx = (loop.index % (colors | length)) %}
                    {% endif %}
                  {% endfor %}
                  {{ colors[idx] }}
                {% else %}
                  {{ colors[0] }}
                {% endif %}
      
      - conditions:
          - condition: template
            value_template: "{{ command == 'press' and trigger.event.data.args.press_type == 'short' and trigger.event.data.args.step_mode == 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              rgb_color: >
                {% set current = state_attr(light, 'rgb_color') %}
                {% if current %}
                  {% set idx = (colors | length) - 1 %}
                  {% for color in colors %}
                    {% if color == current and loop.index > 1 %}
                      {% set idx = loop.index - 2 %}
                    {% endif %}
                  {% endfor %}
                  {{ colors[idx] }}
                {% else %}
                  {{ colors[-1] }}
                {% endif %}
