blueprint:
  name: IKEA Styrbar - Tradfri RGB Lamp Control
  description: Control IKEA Tradfri RGB lamp with Styrbar remote – On/Off and robust color cycling
  domain: automation
  input:
    remote:
      name: IKEA Styrbar Remote
      description: Select the Styrbar remote control
      selector:
        device:
          integration: zha
    target_light:
      name: Tradfri RGB Lamp
      description: Select the Tradfri RGB lamp to control
      selector:
        entity:
          domain: light
          integration: zha

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      light: !input target_light
      colors:
        - [255, 0, 0]      # Rot
        - [255, 127, 0]    # Orange
        - [255, 255, 0]    # Gelb
        - [0, 255, 0]      # Grün
        - [0, 255, 255]    # Cyan
        - [0, 0, 255]      # Blau
        - [255, 0, 255]    # Magenta
        - [255, 255, 255]  # Weiß
      current_color: "{{ state_attr(light, 'rgb_color') | list if state_attr(light, 'rgb_color') else none }}"
      def_color_idx: >
        {% set idx = -1 %}
        {% set min_dist = 1000 %}
        {% if current_color %}
          {% for i in range(colors|length) %}
            {% set dist = ((colors[i][0]-current_color[0])**2 + (colors[i][1]-current_color[1])**2 + (colors[i][2]-current_color[2])**2) ** 0.5 %}
            {% if dist < min_dist %}
              {% set idx = i %}
              {% set min_dist = dist %}
            {% endif %}
          {% endfor %}
          {{ idx }}
        {% else %}
          -1
        {% endif %}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ command == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
      - conditions:
          - condition: template
            value_template: "{{ command == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light }}"
      - conditions:
          - condition: template
            value_template: "{{ command == 'press' and trigger.event.data.args[0] == 257 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              rgb_color: >
                {% if def_color_idx >= 0 %}
                  {{ colors[(def_color_idx + 1) % colors|length] }}
                {% else %}
                  {{ colors[0] }}
                {% endif %}
      - conditions:
          - condition: template
            value_template: "{{ command == 'press' and trigger.event.data.args[0] == 256 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              rgb_color: >
                {% if def_color_idx >= 0 %}
                  {{ colors[(def_color_idx - 1) % colors|length] }}
                {% else %}
                  {{ colors[-1] }}
                {% endif %}
