blueprint:
  name: IKEA Styrbar - Tradfri RGB Lamp Control with Dimmer
  description: Control IKEA Tradfri RGB lamp with Styrbar remote – Color cycling + Dimmer on long press
  domain: automation
  input:
    remote:
      name: IKEA Styrbar Remote
      description: Select the Styrbar remote control
      selector:
        device:
          integration: zha
    target_light:
      name: Tradfri RGB Lamp
      description: Select the Tradfri RGB lamp to control
      selector:
        entity:
          domain: light
          integration: zha

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      light: !input target_light
      colors:
        - [0.701, 0.299]   # Rot
        - [0.561, 0.405]   # Orange
        - [0.448, 0.517]   # Gelb
        - [0.172, 0.747]   # Grün
        - [0.151, 0.343]   # Cyan
        - [0.136, 0.04]    # Blau
        - [0.385, 0.155]   # Magenta
        - [0.512, 0.415]   # Warmweiß 1
        - [0.323, 0.329]   # Kaltweiß
      current_color: >-
        {% if state_attr(light, 'color_mode') == 'xy' %}
          {{ state_attr(light, 'xy_color') | list if state_attr(light, 'xy_color') else none }}
        {% else %}
          none
        {% endif %}
      def_color_idx: >-
        {% set max_dist = 0.05 %}
        {% set ns = namespace(idx=-1, min_dist=max_dist) %}
        {% set xy = state_attr(light, 'xy_color') %}
        {% if xy is not none and state_attr(light, 'color_mode') == 'xy' %}
          {% set current = [xy[0] | float, xy[1] | float] %}
          {% for i in range(colors|length) %}
            {% set dist = ((colors[i][0]-current[0])**2 + (colors[i][1]-current[1])**2) ** 0.5 %}
            {% if dist < ns.min_dist %}
              {% set ns.idx = i %}
              {% set ns.min_dist = dist %}
            {% endif %}
          {% endfor %}
          {{ ns.idx | int }}
        {% else %}
          -1
        {% endif %}

  - choose:
      # Short press ON button - Turn on with first color
      - conditions:
          - condition: template
            value_template: "{{ command == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
          - delay:
              milliseconds: 500
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              xy_color: "{{ colors[0] }}"
              brightness: 254

      # Short press OFF button - Turn off
      - conditions:
          - condition: template
            value_template: "{{ command == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light }}"

      # Long press ON button - Brightness up (move_with_on_off)
      - conditions:
          - condition: template
            value_template: "{{ command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ light }}"
                  data:
                    brightness_step_pct: 10
                - delay:
                    milliseconds: 200

      # Long press OFF button - Brightness down (move)
      - conditions:
          - condition: template
            value_template: "{{ command == 'move' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ light }}"
                  data:
                    brightness_step_pct: -10
                - delay:
                    milliseconds: 200

      # Release long press - Stop dimming (stop or stop_with_on_off)
      - conditions:
          - condition: template
            value_template: "{{ command in ['stop', 'stop_with_on_off'] }}"
        sequence: []

      # Left button press - Next color
      - conditions:
          - condition: template
            value_template: "{{ command == 'press' and trigger.event.data.args[0] == 257 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              xy_color: |
                {% if def_color_idx >= 0 %}
                  {{ colors[(def_color_idx + 1) % colors|length] }}
                {% else %}
                  {{ colors[0] }}
                {% endif %}

      # Right button press - Previous color
      - conditions:
          - condition: template
            value_template: "{{ command == 'press' and trigger.event.data.args[0] == 256 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              xy_color: |
                {% if def_color_idx >= 0 %}
                  {{ colors[(def_color_idx - 1) % colors|length] }}
                {% else %}
                  {{ colors[-1] }}
                {% endif %}