blueprint:
  name: IKEA Rodret - Tradfri RGB Lamp Control
  description: Control IKEA Tradfri RGB lamp with Rodret remote - On/Off and color cycling
  domain: automation
  input:
    remote:
      name: IKEA Rodret Remote
      description: Select the Rodret remote control
      selector:
        device:
          integration: zha
    target_light:
      name: Tradfri RGB Lamp
      description: Select the Tradfri RGB lamp to control
      selector:
        entity:
          domain: light
          integration: zha

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      light: !input target_light
      colors:
        - [255, 0, 0]      # Red
        - [255, 127, 0]    # Orange
        - [255, 255, 0]    # Yellow
        - [0, 255, 0]      # Green
        - [0, 255, 255]    # Cyan
        - [0, 0, 255]      # Blue
        - [255, 0, 255]    # Magenta
        - [255, 255, 255]  # White
      current_color: "{{ state_attr(light, 'rgb_color') | list if state_attr(light, 'rgb_color') else none }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ command == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
      
      - conditions:
          - condition: template
            value_template: "{{ command == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light }}"
      
      - conditions:
          - condition: template
            value_template: "{{ command == 'press' and trigger.event.data.args[0] == 257 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              rgb_color: >
                {% if current_color %}
                  {% set current_idx = colors.index(current_color) if current_color in colors else -1 %}
                  {% if current_idx >= 0 %}
                    {{ colors[(current_idx + 1) % colors|length] }}
                  {% else %}
                    {{ colors[0] }}
                  {% endif %}
                {% else %}
                  {{ colors[0] }}
                {% endif %}
      
      - conditions:
          - condition: template
            value_template: "{{ command == 'press' and trigger.event.data.args[0] == 256 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              rgb_color: >
                {% if current_color %}
                  {% set current_idx = colors.index(current_color) if current_color in colors else -1 %}
                  {% if current_idx >= 0 %}
                    {{ colors[(current_idx - 1) % colors|length] }}
                  {% else %}
                    {{ colors[-1] }}
                  {% endif %}
                {% else %}
                  {{ colors[-1] }}
                {% endif %}
